# ########   ###### #####   #####  ######   ######  ######
# ##     ##  ##     ##  ## ##  ## ##    ## ##    ## ##   ##
# ##     ##  ##     ##   ###   ## ##    ## ##    ## ##    ##
# ########   ####   ##    #    ## ##    ## ##    ## ##    ##
# ##    ##   ##     ##         ## ##    ## ##    ## ##    ##
# ##     ##  ##     ##         ## ##    ## ##    ## ##   ##
# ##      ## ###### ##         ##  ######   ######  ######
#                      http://remood.org/
# -----------------------------------------------------------------------------
# Copyright (C) 2009-2011 GhostlyDeath <ghostlydeath@remood.org>
# -----------------------------------------------------------------------------
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# -----------------------------------------------------------------------------
# Another makefile setup, recursive makes
# This is the core makefile, everything eventually drops down to this specific

###########################
### DIRECTORY LOCATIONS ###
###########################

# Binary location
__INT_BIN = bin

# Object location
__INT_OBJ = obj

# Source code location
__INT_SRC = src

#####################
### COMPILE FLAGS ###
#####################

# CC Flags
__INT_TEMP := $(__INT_CFLAGS)
unexport __INT_TEMP
export __INT_CFLAGS := $(__INT_TEMP) -I$(__INT_SRC) -DGAMECLIENT

# Linker Flags
__INT_TEMP := $(__INT_LDFLAGS)
unexport __INT_TEMP
export __INT_LDFLAGS := $(__INT_TEMP) -lm

####################
### OBJECT FILES ###
####################

__INT_OBJS := $(foreach __X_SOURCE, $(wildcard $(__INT_SRC)/*.c), $(__INT_OBJ)/$(__INT_OBJPREFIX)$(basename $(notdir $(__X_SOURCE))).o) $(foreach __X_SOURCE, $(wildcard $(__INT_SRC)/$(__INT_IFACEDIR)/*.c), $(__INT_OBJ)/$(__INT_OBJPREFIX)$(basename $(notdir $(__X_SOURCE))).o)

###############
### TARGETS ###
###############

all:										remood
											

remood:										$(__INT_BIN)/remood$(_INT_EXESUFFIX)
											

clean:										
											rm -f $(__INT_OBJS)

$(__INT_BIN)/remood$(_INT_EXESUFFIX):		$(__INT_OBJ) $(__INT_OBJS)
											@echo "  [LD] $@"
											$(__INT_CC) -o $@ $(__INT_OBJS) $(__INT_LDFLAGS)

$(__INT_OBJ):								
											mkdir -p $(__INT_OBJ)

$(__INT_OBJ)/$(__INT_OBJPREFIX)%.o:			$(__INT_SRC)/%.c
											@echo "  [CC] $<"
											$(__INT_CC) -c $< -o $@ $(__INT_CFLAGS)

$(__INT_OBJ)/$(__INT_OBJPREFIX)%.o:			$(__INT_SRC)/$(__INT_IFACEDIR)/%.c
											@echo "  [CC] $<"
											$(__INT_CC) -c $< -o $@ $(__INT_CFLAGS)


