#!/bin/sh

# ########   ###### #####   #####  ######   ######  ######
# ##     ##  ##     ##  ## ##  ## ##    ## ##    ## ##   ##
# ##     ##  ##     ##   ###   ## ##    ## ##    ## ##    ##
# ########   ####   ##    #    ## ##    ## ##    ## ##    ##
# ##    ##   ##     ##         ## ##    ## ##    ## ##    ##
# ##     ##  ##     ##         ## ##    ## ##    ## ##   ##
# ##      ## ###### ##         ##  ######   ######  ######
#                      http://remood.org/
# -----------------------------------------------------------------------------
# Project Leader:    GhostlyDeath           (ghostlydeath@remood.org)
# Project Co-Leader: RedZTag                (jostol@remood.org)
# -----------------------------------------------------------------------------
# Copyright (C) 2009 The ReMooD Team.
# Copyright (C) ???? "Jon" (unknown@unknown)
# -----------------------------------------------------------------------------
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# -----------------------------------------------------------------------------
# Debian Post Installation Script `postinst`

# Update Alternatives
set -e

case "$1" in
	configure|abort-upgrade)
		update-alternatives --install /usr/games/doom doom /usr/games/remood 50
		update-alternatives --install /usr/games/boom boom /usr/games/remood 50
		update-alternatives --install /usr/games/heretic heretic /usr/games/remood 50
	;;

	abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0


