// -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-
// -----------------------------------------------------------------------------
//         :oCCCCOCoc.
//     .cCO8OOOOOOOOO8Oo:
//   .oOO8OOOOOOOOOOOOOOOCc
//  cO8888:         .:oOOOOC.                                                TM
// :888888:   :CCCc   .oOOOOC.     ###      ###                    #########
// C888888:   .ooo:   .C########   #####  #####  ######    ######  ##########
// O888888:         .oO###    ###  #####  ##### ########  ######## ####    ###
// C888888:   :8O.   .C##########  ### #### ### ##    ##  ##    ## ####    ###
// :8@@@@8:   :888c   o###         ### #### ### ########  ######## ##########
//  :8@@@@C   C@@@@   oo########   ###  ##  ###  ######    ######  #########
//    cO@@@@@@@@@@@@@@@@@Oc0
//      :oO8@@@@@@@@@@Oo.
//         .oCOOOOOCc.                                      http://remood.org/
// -----------------------------------------------------------------------------
// Copyright (C) 1993-1996 by id Software, Inc.
// Copyright (C) 1998-2000 by DooM Legacy Team.
// Copyright (C) 2008-2012 GhostlyDeath (ghostlydeath@gmail.com)
// -----------------------------------------------------------------------------
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// -----------------------------------------------------------------------------
// DESCRIPTION:
//      Thing frame/state LUT,
//      generated by multigen utilitiy.
//      This one is the original DOOM version, preserved.

// Data.
#include "doomdef.h"
#include "sounds.h"
#include "m_fixed.h"
#include "d_items.h"
#include "p_mobj.h"
#include "z_zone.h"
#include "info.h"
#include "v_video.h"

// Doesn't work with g++, needs actionf_p1
void A_Light0();
void A_WeaponReady();
void A_Lower();
void A_Raise();
void A_Punch();
void A_ReFire();
void A_FirePistol();
void A_Light1();
void A_FireShotgun();
void A_Light2();
void A_FireShotgun2();
void A_CheckReload();
void A_OpenShotgun2();
void A_LoadShotgun2();
void A_CloseShotgun2();
void A_FireCGun();
void A_GunFlash();
void A_FireMissile();
void A_Saw();
void A_FirePlasma();
void A_BFGsound();
void A_FireBFG();
void A_BFGSpray();
void A_Explode();
void A_Pain();
void A_PlayerScream();
void A_Fall();
void A_XScream();
void A_Look();
void A_Chase();
void A_FaceTarget();
void A_PosAttack();
void A_Scream();
void A_SPosAttack();
void A_VileChase();
void A_VileStart();
void A_VileTarget();
void A_VileAttack();
void A_StartFire();
void A_Fire();
void A_FireCrackle();
void A_Tracer();
void A_SkelWhoosh();
void A_SkelFist();
void A_SkelMissile();
void A_FatRaise();
void A_FatAttack1();
void A_FatAttack2();
void A_FatAttack3();
void A_BossDeath();
void A_CPosAttack();
void A_CPosRefire();
void A_TroopAttack();
void A_SargAttack();
void A_HeadAttack();
void A_BruisAttack();
void A_SkullAttack();
void A_Metal();
void A_SpidRefire();
void A_BabyMetal();
void A_BspiAttack();
void A_Hoof();
void A_CyberAttack();
void A_PainAttack();
void A_PainDie();
void A_KeenDie();
void A_BrainPain();
void A_BrainScream();
void A_BrainDie();
void A_BrainAwake();
void A_BrainSpit();
void A_SpawnSound();
void A_SpawnFly();
void A_BrainExplode();

void A_SmokeTrailer();
void A_SmokeTrailerRocket();
void A_SmokeTrailerSkull();

void A_FireOldBFG();

/*****************************************************************************/

state_t** states = 0;
size_t NUMSTATES = 0;
mobjinfo_t** mobjinfo = NULL;
mobjtype_t NUMMOBJTYPES = 0;

/*****************************************************************************/

/* INFO_GetTypeByName() -- Returns a map object by it's name */
mobjtype_t INFO_GetTypeByName(const char* const a_Name)
{
	size_t i = 0;
	uint32_t Hash;
	
	/* Check */
	if (!a_Name)
		return NUMMOBJTYPES;
	
	/* Hash name */
	Hash = Z_Hash(a_Name);
	
	/* Go through class list */
	for (i = 0; i < NUMMOBJTYPES; i++)
	{
#if 0
		// Needs hashing?
		if (!l_DeprClassHash[i][0])
		{
			l_DeprClassHash[i][0] = Z_Hash(MT2ReMooDClass[i]);
			l_DeprClassHash[i][1] = Z_Hash(MT2MTString[i]);
		}
		
		// Compare against ReMooD Class
		if (Hash == l_DeprClassHash[i][0] && strcasecmp(a_Name, MT2ReMooDClass[i]) == 0)
			return i;
			
		// Compare against MT Name
		if (Hash == l_DeprClassHash[i][1] && strcasecmp(a_Name, MT2MTString[i]) == 0)
			return i;
#endif
	}
	
	/* Not found? */
	return NUMMOBJTYPES;
}

/* INFO_SpriteNumByName() -- Determine sprite ID by name */
spritenum_t INFO_SpriteNumByName(const char* const a_Name)
{
	size_t i;
	
	/* Check */
	if (!a_Name)
		return 0;
	
	/* Determine sprite */
	//for (i = 0; sprnames[i]; i++)
	//	if (strcasecmp(a_Name, sprnames[i]) == 0)
	//		return i;
		
	/* Not found? */
	return 0;
}

/* INFO_FunctionPtrByName() -- Get action pointer by name */
actionf_t INFO_FunctionPtrByName(const char* const a_Name)
{
	actionf_t RetVal;
	
	memset(&RetVal, 0, sizeof(RetVal));
	
	/* Check */
	if (!a_Name)
		return RetVal;
	
	if (strcasecmp("Light0", a_Name) == 0) RetVal.acv = A_Light0;
	else if (strcasecmp("WeaponReady", a_Name) == 0) RetVal.acv = A_WeaponReady;
	else if (strcasecmp("Lower", a_Name) == 0) RetVal.acv = A_Lower;
	else if (strcasecmp("Raise", a_Name) == 0) RetVal.acv = A_Raise;
	else if (strcasecmp("Punch", a_Name) == 0) RetVal.acv = A_Punch;
	else if (strcasecmp("ReFire", a_Name) == 0) RetVal.acv = A_ReFire;
	else if (strcasecmp("FirePistol", a_Name) == 0) RetVal.acv = A_FirePistol;
	else if (strcasecmp("Light1", a_Name) == 0) RetVal.acv = A_Light1;
	else if (strcasecmp("FireShotgun", a_Name) == 0) RetVal.acv = A_FireShotgun;
	else if (strcasecmp("Light2", a_Name) == 0) RetVal.acv = A_Light2;
	else if (strcasecmp("FireShotgun2", a_Name) == 0) RetVal.acv = A_FireShotgun2;
	else if (strcasecmp("CheckReload", a_Name) == 0) RetVal.acv = A_CheckReload;
	else if (strcasecmp("OpenShotgun2", a_Name) == 0) RetVal.acv = A_OpenShotgun2;
	else if (strcasecmp("LoadShotgun2", a_Name) == 0) RetVal.acv = A_LoadShotgun2;
	else if (strcasecmp("CloseShotgun2", a_Name) == 0) RetVal.acv = A_CloseShotgun2;
	else if (strcasecmp("FireCGun", a_Name) == 0) RetVal.acv = A_FireCGun;
	else if (strcasecmp("GunFlash", a_Name) == 0) RetVal.acv = A_GunFlash;
	else if (strcasecmp("FireMissile", a_Name) == 0) RetVal.acv = A_FireMissile;
	else if (strcasecmp("Saw", a_Name) == 0) RetVal.acv = A_Saw;
	else if (strcasecmp("FirePlasma", a_Name) == 0) RetVal.acv = A_FirePlasma;
	else if (strcasecmp("BFGsound", a_Name) == 0) RetVal.acv = A_BFGsound;
	else if (strcasecmp("FireBFG", a_Name) == 0) RetVal.acv = A_FireBFG;
	else if (strcasecmp("BFGSpray", a_Name) == 0) RetVal.acv = A_BFGSpray;
	else if (strcasecmp("Explode", a_Name) == 0) RetVal.acv = A_Explode;
	else if (strcasecmp("Pain", a_Name) == 0) RetVal.acv = A_Pain;
	else if (strcasecmp("PlayerScream", a_Name) == 0) RetVal.acv = A_PlayerScream;
	else if (strcasecmp("Fall", a_Name) == 0) RetVal.acv = A_Fall;
	else if (strcasecmp("XScream", a_Name) == 0) RetVal.acv = A_XScream;
	else if (strcasecmp("Look", a_Name) == 0) RetVal.acv = A_Look;
	else if (strcasecmp("Chase", a_Name) == 0) RetVal.acv = A_Chase;
	else if (strcasecmp("FaceTarget", a_Name) == 0) RetVal.acv = A_FaceTarget;
	else if (strcasecmp("PosAttack", a_Name) == 0) RetVal.acv = A_PosAttack;
	else if (strcasecmp("Scream", a_Name) == 0) RetVal.acv = A_Scream;
	else if (strcasecmp("SPosAttack", a_Name) == 0) RetVal.acv = A_SPosAttack;
	else if (strcasecmp("VileChase", a_Name) == 0) RetVal.acv = A_VileChase;
	else if (strcasecmp("VileStart", a_Name) == 0) RetVal.acv = A_VileStart;
	else if (strcasecmp("VileTarget", a_Name) == 0) RetVal.acv = A_VileTarget;
	else if (strcasecmp("VileAttack", a_Name) == 0) RetVal.acv = A_VileAttack;
	else if (strcasecmp("StartFire", a_Name) == 0) RetVal.acv = A_StartFire;
	else if (strcasecmp("Fire", a_Name) == 0) RetVal.acv = A_Fire;
	else if (strcasecmp("FireCrackle", a_Name) == 0) RetVal.acv = A_FireCrackle;
	else if (strcasecmp("Tracer", a_Name) == 0) RetVal.acv = A_Tracer;
	else if (strcasecmp("SkelWhoosh", a_Name) == 0) RetVal.acv = A_SkelWhoosh;
	else if (strcasecmp("SkelFist", a_Name) == 0) RetVal.acv = A_SkelFist;
	else if (strcasecmp("SkelMissile", a_Name) == 0) RetVal.acv = A_SkelMissile;
	else if (strcasecmp("FatRaise", a_Name) == 0) RetVal.acv = A_FatRaise;
	else if (strcasecmp("FatAttack1", a_Name) == 0) RetVal.acv = A_FatAttack1;
	else if (strcasecmp("FatAttack2", a_Name) == 0) RetVal.acv = A_FatAttack2;
	else if (strcasecmp("FatAttack3", a_Name) == 0) RetVal.acv = A_FatAttack3;
	else if (strcasecmp("BossDeath", a_Name) == 0) RetVal.acv = A_BossDeath;
	else if (strcasecmp("CPosAttack", a_Name) == 0) RetVal.acv = A_CPosAttack;
	else if (strcasecmp("CPosRefire", a_Name) == 0) RetVal.acv = A_CPosRefire;
	else if (strcasecmp("TroopAttack", a_Name) == 0) RetVal.acv = A_TroopAttack;
	else if (strcasecmp("SargAttack", a_Name) == 0) RetVal.acv = A_SargAttack;
	else if (strcasecmp("HeadAttack", a_Name) == 0) RetVal.acv = A_HeadAttack;
	else if (strcasecmp("BruisAttack", a_Name) == 0) RetVal.acv = A_BruisAttack;
	else if (strcasecmp("SkullAttack", a_Name) == 0) RetVal.acv = A_SkullAttack;
	else if (strcasecmp("Metal", a_Name) == 0) RetVal.acv = A_Metal;
	else if (strcasecmp("SpidRefire", a_Name) == 0) RetVal.acv = A_SpidRefire;
	else if (strcasecmp("BabyMetal", a_Name) == 0) RetVal.acv = A_BabyMetal;
	else if (strcasecmp("BspiAttack", a_Name) == 0) RetVal.acv = A_BspiAttack;
	else if (strcasecmp("Hoof", a_Name) == 0) RetVal.acv = A_Hoof;
	else if (strcasecmp("CyberAttack", a_Name) == 0) RetVal.acv = A_CyberAttack;
	else if (strcasecmp("PainAttack", a_Name) == 0) RetVal.acv = A_PainAttack;
	else if (strcasecmp("PainDie", a_Name) == 0) RetVal.acv = A_PainDie;
	else if (strcasecmp("KeenDie", a_Name) == 0) RetVal.acv = A_KeenDie;
	else if (strcasecmp("BrainPain", a_Name) == 0) RetVal.acv = A_BrainPain;
	else if (strcasecmp("BrainScream", a_Name) == 0) RetVal.acv = A_BrainScream;
	else if (strcasecmp("BrainDie", a_Name) == 0) RetVal.acv = A_BrainDie;
	else if (strcasecmp("BrainAwake", a_Name) == 0) RetVal.acv = A_BrainAwake;
	else if (strcasecmp("BrainSpit", a_Name) == 0) RetVal.acv = A_BrainSpit;
	else if (strcasecmp("SpawnSound", a_Name) == 0) RetVal.acv = A_SpawnSound;
	else if (strcasecmp("SpawnFly", a_Name) == 0) RetVal.acv = A_SpawnFly;
	else if (strcasecmp("BrainExplode", a_Name) == 0) RetVal.acv = A_BrainExplode;
	else if (strcasecmp("SmokeTrailer", a_Name) == 0) RetVal.acv = A_SmokeTrailer;
	else if (strcasecmp("SmokeTrailerRocket", a_Name) == 0) RetVal.acv = A_SmokeTrailerRocket;
	else if (strcasecmp("SmokeTrailerSkull", a_Name) == 0) RetVal.acv = A_SmokeTrailerSkull;
	else if (strcasecmp("FireOldBFG", a_Name) == 0) RetVal.acv = A_FireOldBFG;
	
	/* Not found? */
	return RetVal;
}

/* INFO_PriorityByName() -- Priority by name */
int INFO_PriorityByName(const char* const a_Name)
{
	/* Check */
	if (!a_Name)
		return STP_DEFAULT;
	
	/* Compare */
	if (strcasecmp(a_Name, "Null") == 0) return STP_NULL;
	else if (strcasecmp(a_Name, "Default") == 0) return STP_DEFAULT;
	else if (strcasecmp(a_Name, "Weapons") == 0) return STP_WEAPON;
	else if (strcasecmp(a_Name, "Ammo") == 0) return STP_AMMO;
	else if (strcasecmp(a_Name, "WeaponFlash") == 0) return STP_WEPFLASH;
	else if (strcasecmp(a_Name, "Effects") == 0) return STP_EFFECTS;
	else if (strcasecmp(a_Name, "Monsters") == 0) return STP_MONSTERS;
	else if (strcasecmp(a_Name, "Corpses") == 0) return STP_CORPSES;
	else if (strcasecmp(a_Name, "Players") == 0) return STP_PLAYERS;
	else if (strcasecmp(a_Name, "Health") == 0) return STP_HEALTH;
	else if (strcasecmp(a_Name, "Cookies") == 0) return STP_COOKIES;
	else if (strcasecmp(a_Name, "MissionCritical") == 0) return STP_MISSIONCRITICAL;
	else if (strcasecmp(a_Name, "Powerups") == 0) return STP_POWERUPS;
	else if (strcasecmp(a_Name, "Decorations") == 0) return STP_DECORATIONS;
	else if (strcasecmp(a_Name, "Projectiles") == 0) return STP_PROJECTILES;
	
	/* Not Found */
	return STP_DEFAULT;
}

/* INFO_TransparencyByName() -- Return transparency for name */
uint32_t INFO_TransparencyByName(const char* const a_Name)
{
	int32_t TransNum;
	
	/* Check */
	if (!a_Name)
		return 0;
	
	/* Check name first */
	if (strcasecmp(a_Name, "Fire") == 0)
		return VEX_TRANSFIRE;
	else if (strcasecmp(a_Name, "Effect1") == 0)
		return VEX_TRANSFX1;
	
	/* Compare Number */
	TransNum = atoi(a_Name);
	
	// Round up?
	if ((TransNum % 10) >= 5)
		TransNum += 5;
	
	// Shrink
	TransNum /= 10;
	
	// Limit
	if (TransNum < 0)
		TransNum = 0;
	if (TransNum > 10)
		TransNum = 10;
	
	// Return
	return TransNum;
}

typedef struct FlagInfo_s
{
	uint32_t Field;
	const char* const Name;
} FlagInfo_t;

const FlagInfo_t xFlags[] =
{
	{MF_SPECIAL, "IsSpecial"},
	{MF_SOLID, "IsSolid"},
	{MF_SHOOTABLE, "IsShootable"},
	{MF_NOSECTOR, "NoSectorLinks"},
	{MF_NOBLOCKMAP, "NoBlockMap"},
	{MF_AMBUSH, "IsDeaf"},
	{MF_JUSTHIT, "JustGotHit"},
	{MF_JUSTATTACKED, "JustAttacked"},
	{MF_SPAWNCEILING, "SpawnsOnCeiling"},
	{MF_NOGRAVITY, "NoGravity"},
	{MF_DROPOFF, "IsDropOff"},
	{MF_PICKUP, "CanPickupItems"},
	{MF_NOCLIP, "NoClipping"},
	{MF_SLIDE, "CanSlideAlongWalls"},
	{MF_FLOAT, "IsFloating"},
	{MF_TELEPORT, "NoLineCrossing"},
	{MF_MISSILE, "IsMissile"},
	{MF_DROPPED, "IsDropped"},
	{MF_SHADOW, "IsFuzzyShadow"},
	{MF_NOBLOOD, "NoBleeding"},
	{MF_CORPSE, "IsCorpse"},
	{MF_INFLOAT, "NoFloatAdjust"},
	{MF_COUNTKILL, "IsKillCountable"},
	{MF_COUNTITEM, "IsItemCountable"},
	{MF_SKULLFLY, "IsFlyingSkull"},
	{MF_NOTDMATCH, "NotInDeathmatch"},
	{MF_NOCLIPTHING, "NoThingClipping"},
	{0, NULL},
};

const FlagInfo_t xFlagsTwo[] =
{
	{MF2_LOGRAV, "IsLowGravity"},
	{MF2_WINDTHRUST, "IsWindThrustable"},
	{MF2_FLOORBOUNCE, "IsFloorBouncer"},
	{MF2_THRUGHOST, "PassThruGhosts"},
	{MF2_FLY, "IsFlying"},
	{MF2_FOOTCLIP, "CanFeetClip"},
	{MF2_SPAWNFLOAT, "SpawnAtRandomZ"},
	{MF2_NOTELEPORT, "CannotTeleport"},
	{MF2_RIP, "MissilesThruSolids"},
	{MF2_PUSHABLE, "Pushable"},
	{MF2_SLIDE, "WallSliding"},
	{MF2_ONMOBJ, "IsOnObject"},
	{MF2_PASSMOBJ, "MoveOverUnderObject"},
	{MF2_CANNOTPUSH, "CannotPushPushables"},
	{MF2_FEETARECLIPPED, "AreFeetClipped"},
	{MF2_BOSS, "IsBoss"},
	{MF2_FIREDAMAGE, "DealsFireDamage"},
	{MF2_NODMGTHRUST, "NoDamageThrust"},
	{MF2_TELESTOMP, "CanTeleStomp"},
	{MF2_FLOATBOB, "FloatBobbing"},
	{MF2_DONTDRAW, "DoNotDraw"},
	{MF2_BOUNCES, "CanBounce"},
	{MF2_FRIENDLY, "IsFriendly"},
	{MF2_FORCETRANSPARENCY, "ForceTransparency"},
	{MF2_FLOORHUGGER, "IsFloorHugger"},
	{0, NULL},
};

const FlagInfo_t xRXFlagsA[] =
{
	{MFREXA_ENABLEFASTSPEED, "EnableFastSpeed"},
	{MFREXA_NOFORCEALLTRIGGERC, "NoForcedAllTriggers"},
	{MFREXA_NOCROSSTRIGGER, "NoLineCrossTrigger"},
	{MFREXA_ISPUSHPULL, "IsPusherPuller"},
	{MFREXA_DOPUSHAWAY, "PushesAway"},
	{MFREXA_ISTELEPORTMAN, "IsTeleportMan"},
	{MFREXA_ALWAYSTELEPORT, "AlwaysTeleport"},
	{MFREXA_ISMONSTER, "IsMonster"},
	{MFREXA_ISTELEFOG, "IsTeleportFog"},
	{MFREXA_ISPOWERUP, "IsPowerup"},
	{MFREXA_HALFMISSILERANGE, "HalfMissileRange"},
	{MFREXA_SOUNDEVERYWHERE, "PlaySoundsEverywhere"},
	{MFREXA_NOWATERSPLASH, "NoWaterSplashing"},
	{MFREXA_NOCHECKWATER, "NoWaterChecking"},
	{MFREXA_USENULLMOTHINKER, "UseMobjNullThinker"},
	{MFREXA_NOPLAYERWALK, "NoPlayerWalkAnimation"},
	{MFREXA_NOSMOOTHSTEPUP, "NoSmoothStepUp"},
	{MFREXA_NOALTDMRESPAWN, "NoRespawnInAltDM"},
	{MFREXA_CARRYKILLER, "CarriesKiller"},
	{MFREXA_MARKRESTOREWEAPON, "MarkRestoreWeapon"},
	{MFREXA_NORANDOMPLAYERLOOK, "NoRandomPlayerLook"},
	{MFREXA_ALLOWNOCROSSCROSS, "AllowNonCrossableCrossing"},
	{MFREXA_NEVERCROSSTRIGGER, "NeverCrossTrigger"},
	{MFREXA_CANCEILINGSTEP, "CanCeilingStep"},
	{MFREXA_NOTHRESHOLD, "NoThreshold"},
	{MFREXA_NOTRETAILIATETARGET, "NotARetaliateTarget"},
	{MFREXA_RADIUSATTACKPROOF, "ExplosionProof"},
	{MFREXA_RANDOMPUFFTIME, "RandomPuffTime"},
	{MFREXA_KEEPGRAVONDEATH, "KeepGravityWhenKilled"},
	{MFREXA_ISPLAYEROBJECT, "IsPlayerObject"},
	{MFREXA_ISBRAINTARGET, "IsBossBrainTarget"},
	{0, NULL},
};

const FlagInfo_t xRXFlagsB[] =
{
	{MFREXB_DOMAPSEVENSPECA, "DoDeadSimpleSpecialSix"},
	{MFREXB_DOMAPSEVENSPECB, "DoDeadSimpleSpecialSeven"},
	{MFREXB_DOBARONSPECIAL, "DoBaronSpecial"},
	{MFREXB_DOCYBERSPECIAL, "DoCyberSpecial"},
	{MFREXB_DOSPIDERSPECIAL, "DoSpiderSpecial"},
	{MFREXB_DODOORSIXTHREEOPEN, "DoSixSixSixDoorOpen"},
	{MFREXB_INITBOTNODES, "ForceInitializeBotNodes"},
	{0, NULL},
};

